# file: roles/node/tasks/main.yml
---
# For example,
# 
# - name: be sure ntp is installed
#   yum: pkg=ntp state=installed
#   tags: ntp
# 
# - name: be sure ntp is configured
#   template: src=ntp.conf.j2 dest=/etc/ntp.conf
#   notify:
#     - restart ntpd
#   tags: ntp
# 
# - name: be sure ntpd is running and enabled
#   service: name=ntpd state=running enabled=yes
#   tags: ntp

- name: Iniciar imagen unc-cdn/node
  command: docker run -d --name node -p 3000:3000 -v /opt/cdn:/opt/cdn -v /var/run/docker.sock:/var/run/docker.sock unc_cdn/node
#  docker: 
#    name: node
#    image: unc_cdn/node
#    state: restarted
#    ports: 8084:8084
#    detach: true
#    volumes:
#      - /opt/cdn:/opt/cdn
#      - /var/run/docker.sock:/var/run/docker.sock
